### ISSUE TITLE
HmrcHeader Signout button does not translate to Welsh

### ISSUE THREAD

**Issue by elabeca** [hmrc/hmrc-frontend#106]
When selecting the Welsh language, the Signout button at the top right of the screen does not translate to Welsh

**Comment by matthewmascord** [comment]
Hi @elabeca , is this definitely an issue? I can see the code that switches the language [here](https://github.com/hmrc/hmrc-frontend/blob/b2904b0ab75532e35d9e3223206ce08c533e652b/src/components/header/template.njk#L86)

**Comment by elabeca** [comment]
I've been asked to use this method: https://github.com/hmrc/contact-frontend/blob/7c4ce8ec31b2aa4828e3415e338cec2db8fa6061/app/views/partials/Layout.scala.html#L28 and this should solve the issue
