### ISSUE TITLE
hmrcHeader navigation items not styled correctly

### ISSUE THREAD

**Issue by matthewmascord** [hmrc/hmrc-frontend#114]
When using navigation items with the hmrcHeader component they are not styled correctly. They appear
on the same line as the serviceName. For example

```twig
{{ hmrcHeader({
  language: 'en',
  serviceName: "Service name",
  signOutHref: "#",
  displayHmrcBanner: true,
  navigation: [
    { text: 'Nav 1', href: '#' },
    { text: 'Nav 2', href: '#' },
    { text: 'Nav 3', href: '#' }
  ]
  }) }}
```

is rendered as
![image](https://user-images.githubusercontent.com/27346863/101648279-90147380-3a31-11eb-8f98-5a1ea6a7bb05.png)

Correct rendering would be more like:
![image](https://user-images.githubusercontent.com/27346863/101648565-da95f000-3a31-11eb-900c-409c0cd16f23.png)

**Comment by oscarduignan** [comment]
this is sorted now I think, just doing some tidying of open issues randomly

though have noticed that apparently the menu items for our component are in italics it looks

https://github.com/hmrc/hmrc-frontend/blob/main/backstop_data/bitmaps_reference/backstop_default_header_navigation_item_with_html_example_0_document_1_tablet.png

will investigate that separately!
