### ISSUE TITLE
hmrcHeader mobile navigation non-functional

### ISSUE THREAD

**Issue by matthewmascord** [hmrc/hmrc-frontend#115]
The dropdown menu visible on mobile devices does not open or close:
![image](https://user-images.githubusercontent.com/27346863/101648695-fd280900-3a31-11eb-8c9c-cfbd187f0019.png)

This is due to the Javascript assets from govukHeader not being copied across to hmrcHeader.

**Comment by ellamdav** [comment]
Working currently - uses `govuk-js-header-toggle` to trigger JS from govuk-frontend
<img width="610" alt="image" src="https://github.com/hmrc/hmrc-frontend/assets/22939373/0b818f13-9ebb-4270-a03b-511e9c125e38">
<img width="610" alt="image" src="https://github.com/hmrc/hmrc-frontend/assets/22939373/cc67ab6b-4f52-43b0-ac24-5004a5d6b075">
