### ISSUE TITLE
HMRC banner pattern uses png graphic

### ISSUE THREAD

**Issue by lrdj** [hmrc/hmrc-frontend#119]
The "HMRC banner" pattern here https://design.tax.service.gov.uk/hmrc-design-patterns/hmrc-banner/

Uses a png graphic for the crown:
![graphic from tax platform](https://design.tax.service.gov.uk/extension-assets/hmrc-frontend/hmrc/components/banner/images/hmrc_crest_18px_x2.png)

The gov.uk design system uses an [svg path with a png backup](https://design-system.service.gov.uk/components/header/)

I may have got the wrong end of the stick but I can't get a crisp rendering of the HMRC header in my prototype. Am I doing this wrong or should the pattern include an svg path version of the crown?

**Comment by timsb** [comment]
Hi @lrdj,

Thanks for raising this issue.
Replacing the png in the HMRC Banner with an SVG would be an improvement and we'll add this to our backlog. However, the png should look crisp on HiDPI screens as we're providing a hi-res and low-res version. Can I ask what browser, Operating System, and screen resolution you're seeing this on?

**Comment by lrdj** [comment]
> Can I ask what browser, Operating System, and screen resolution you're seeing this on?

Hiya, my details:

Brave: 
Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)
Safari: 
Version 14.0.2 (15610.3.7.1.10, 15610)
Firefox: 
Version 85.0 (64-bit)

Mac OSX 10.15.7

MacBook Pro (Retina, 13-inch, Early 2015) - Built-in Display
13.3-inch (2560 x 1600)
Intel Iris Graphics 6100 1536 MB graphics

Hope that helps:-)
Dug

**Comment by ellamdav** [comment]
Closing this old issue as the banner now includes the crown/roundel as an SVG, and the PNG fallbacks for legacy IE support have been removed
