### ISSUE TITLE
hmrc-frontend and govuk-frontend have inconsistent linting

### ISSUE THREAD

**Issue by JoPintoPaul** [hmrc/hmrc-frontend#128]
The libraries `hmrc-frontend` and `govuk-frontend` have different sets of linting rules applied and enforced. However, the means that when attempting to copy across a component with minimal changes (as the with the addition of a `CharacterCount` supporting Welsh language in `hmrc-frontend`) linting needs to be disabled to enable the code to be copied directly.

**Comment by ellamdav** [comment]
Closing this and moving it to our tech debt board
