### ISSUE TITLE
timeout-dialog component can show negative time

### ISSUE THREAD

**Issue by PianoManDanDan** [hmrc/hmrc-frontend#275]
If a page with the timeout dialog is left open, but idle it can show negative time remaining. Example screenshots shown below.

## Steps to reproduce

1. Set the timeout dialog to activate the session timeout after a reasonable amount of time (I've been setting it to 20 minutes, with the popup appearing after 18 minutes).
2. Open the page in a browser and minimise it/open other tabs and don't refocus the tab with the timeout dialog until the popup should have appeared
3. Refocus the tab but let the timer hit 0.
4. The timer will continue to count down below 0.

I believe this is due to browser memory management pausing the JavaScript and putting the `setTimeout()` function on hold while the tab is made a background tab (see [this StackOverflow thread](https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs)). However, the time the session should timeout is stored as a DateTime, with the "time until session expires" just being a diff of the two values, which is why it shows negative.

<img width="391" alt="timeout-modal" src="https://user-images.githubusercontent.com/32208138/212901120-42628f06-4cb9-4cb9-aeff-56fb1f1eebcf.png">

**Comment by oscarduignan** [comment]
@PianoManDanDan thank you very much for raising this, apologies we missed it! Snow blind to github notifications sometimes. I think the issue will have been sorted by this bug fix  https://github.com/hmrc/hmrc-frontend/pull/288 it should never count below 0 now
