### ISSUE TITLE
Feature: Do not show Sign out link on timeout-dialog component if required

### ISSUE THREAD

**Issue by bsamray** [hmrc/hmrc-frontend#316]
We are using the HMRC session-timeout modal to warn users when their session is about to expire, and the solution is working well, but there is a requirement to hide the signOutButtonLink (as it is confusing to the users in our journey the way the page text have been set up). All we want to display is the Continue button to refresh the session, or alternatively the timer can count to 0 and then the session expires (i.e. user is not given the option to Sign out - we don't have a sign in feature in our journey - before the counter runs out). It doesn’t look like it’s possible to turn this link off - if we leave the nunjuck parameter blank or remove it then it just defaults to the value set in the HMRC code (i.e. Sign out).
With this issue, we aim to add a parameter to the component, just like many others such as signOutButtonText. This parameter, when set, shall result in not showing the 'Sign out' link on the modal timeout dialog.

**Comment by oscarduignan** [comment]
Hey @bsamray out of curiosity can I ask what service you're using it on- presumably outside hmrc? I've flagged this up internally, thank you for raising the request and sending a PR - we'll take a look at it next week and keep you updated

**Comment by bsamray** [comment]
Hi Hmrc/Hmrc-Frontend,

We are using this in the DWP Access to Work service. We use the Gitlab, so
I am raising this from my personal GitHub account. Thanks for looking at
this PR and please advise any changes needed. We shall promptly look into
it.

Thanks

**Comment by JoPintoPaul** [comment]
Hi @bsamray, thank you for this contribution. We've now added your suggestion into the `hmrc-frontend` library, from [v5.52.0](https://github.com/hmrc/hmrc-frontend/releases/tag/v5.52.0) onwards.

**Comment by bsamray** [comment]
Thanks 👍
