### ISSUE TITLE
Sign out link focus state

### ISSUE THREAD

**Issue by adamliptrot-oc** [hmrc/hmrc-frontend#90]
Sign out link in the HMRC header does not have the correct focus state.

![Screenshot 2020-08-10 at 15 48 43](https://user-images.githubusercontent.com/14074579/89884873-10c97d00-dbc2-11ea-8744-102ebc520020.png)

Adding this to the service CSS acts as a temporary fix

```
.hmrc-header.hmrc-header--with-additional-navigation .hmrc-sign-out-nav__link:focus {
    color: #0B0C0C;
}
```

**Comment by timsb** [comment]
Thanks Adam, looks like gov.uk have raised an issue https://github.com/alphagov/govuk-frontend/issues/1916. Would be good to use this eventually but we can do a quick fix before that.
